### PR TITLE
Add gapple cooldown

### LINKED ISSUE #26: Add golden apple cooldown
Without a cooldown, golden apples allow tanking too much damage for too long. The pearl cooldown code can probably be adapted to work on gapples too

### PR DESCRIPTION
**Pull request by Diet-Cola**
Mostly stolen implementation from pearl cooldown listener, however this needs a rework into being more accepting of any material rather than just pearls and gapples.

### CODE REVIEW

**Review by Aleksey-Terzi — APPROVED** [review]
The code perfectly works.
The only I would suggest renaming **itemCooldowns** to **gappleCooldown** until we make it work with any item.

Btw, I can help to make it work with any item.

**Review by Aleksey-Terzi — APPROVED** [review]
Thanks, looks good

**Comment by wingzero54** [comment]
What is the purpose/ reasoning behind this PR?

**Comment by Aleksey-Terzi** [comment]
Gapple is the cheap regen and the food at the same time.

**Comment by awoo-civ** [comment]
> What is the purpose/ reasoning behind this PR?

In actual combat spamming apples grants you near-invincibility.

You can see an example of it here: https://youtu.be/fS_yRKhH9sI?t=262

**Pull request merged**
